# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)
shape = A.shape
size = A.size
print("shape of the matrix:",shape)
print("size of the matrix:",size)
B = A.dtype
print("datatype of the matrix:",B)

shape of the matrix: (3, 5)
size of the matrix: 15
datatype of the matrix: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [3]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2
sub = np.subtract(B,C)
multi = np.multiply(B,C)
print(B)
print()
print(C)
print()
print(sub)
print()
print(multi)
print()
print(B@C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [4]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
exp_B = np.exp(B)
min_value = np.min(B)
min_in_each_row = np.min(B, axis=1)
min_in_each_column = np.min(B, axis=0)
index_of_min = np.argmin(B)
indexes_of_min_in_each_row = np.argmin(B, axis=1)
total_sum = np.sum(B)
mean_of_each_column = np.mean(B, axis=1)
median_of_each_column = np.median(B, axis=1)
print("\nExponentiated Matrix:")
print(exp_B)
print("\nMinimum Value in the Whole Matrix:", min_value)
print("\nMinimum Value in Each Row:", min_in_each_row)
print("\nMinimum Value in Each Column:", min_in_each_column)
print("\nIndex of Minimum Value in the Whole Matrix:", index_of_min)
print("\nIndexes of Minimum Values in Each Row:", indexes_of_min_in_each_row)
print("\nTotal Sum:", total_sum)
print("\nMean of Each Column:", mean_of_each_column)
print("\nMedian of Each Column:", median_of_each_column)


Exponentiated Matrix:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum Value in the Whole Matrix: 1

Minimum Value in Each Row: [1 4 7]

Minimum Value in Each Column: [1 2 3]

Index of Minimum Value in the Whole Matrix: 0

Indexes of Minimum Values in Each Row: [0 0 0]

Total Sum: 45

Mean of Each Column: [2. 5. 8.]

Median of Each Column: [2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [6]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [7]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

It means you are selecting a range along one dimension while keeping all elements along the other.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [8]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [10]:
for i in A.ravel():
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [11]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Svar:a gör en ställning på 30 value som börjar med 0 och slutar med 29
b: 2 betyder att det är 2 arrays och varje array består av 3 arrays och -1 
betyder att den kommer räkna dimensions av sig själv.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [12]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)
print()
print(m1.shape)
print(m2.shape)

[[2 3]
 [4 5]]

(2, 2)
(2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [13]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [14]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)
print()
print(A+b)

[[1 2]
 [3 4]]
[2 2]

[[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.8, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.15, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [15]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [16]:
def add_mult_matrices(A, B, add_or_multiply):
    
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise Exception('Please provide two matrices.')
    
    if add_or_multiply == '+':
        if not A.shape == B.shape:
            raise ValueError('Same shape required for matrix addition.')
        else: 
            return A + B
        
    elif add_or_multiply == '*':
        if not A.shape[1] == B.shape[0]:
            raise ValueError('Columns and rows must be the same length in matrix multiplication')
        else:
            return A @ B
        
    else:
        raise Exception('the add_or_multiply argument must be "add" or "multiply". ')

In [17]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = [4, 6, 3]
add_mult_matrices(A, B, "*")
#här följer jag första regeln som säger att första ska vara numpy och andra är e vanlig array


Exception: Please provide two matrices.

In [18]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([4, 6, 3])
add_mult_matrices(A, B, "+")
#array är olika deminsion därför funkade inte + så den visade så som det står 

ValueError: Same shape required for matrix addition.

In [19]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([4, 6])
add_mult_matrices(A, B, "*")
#cloumns i den första ör inte lika som den andras row.

ValueError: Columns and rows must be the same length in matrix multiplication

In [20]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([4, 6, 3])
add_mult_matrices(A, B, "/")
#ingen av dem är + eller * så den visade det svaret

Exception: the add_or_multiply argument must be "add" or "multiply". 

**Chap2. Question 2**

In [21]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

In [22]:
AB = add_mult_matrices(A, B, '*')
AC = add_mult_matrices(A, C, '*')

print('AB:', '\n', AB)
print('AC:', '\n', AC)

# AB = AC yet B is not equal to C.
res = np.array_equal(AB, AC)

res2 = np.array_equal(B, C)
#vi gjorde a b och c och vi gångrade dem med varandra så fick vi dem här svaren nedan
#.all gör att du inte får false false och den visar 1 false istället
print(res)
print(res2)

AB: 
 [[ 4  7]
 [ 8 14]]
AC: 
 [[ 4  7]
 [ 8 14]]
True
False


**Chap2. Question 3**

In [23]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

In [24]:
print('AD:', '\n', add_mult_matrices(A, D, '*'))
print('DA', '\n', add_mult_matrices(D, A, '*'))

AD: 
 [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
DA 
 [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [25]:
M1 = np.array([[1, -1], [-1, 1]])
M2 = np.array([[-1, 1], [1, -1]])

In [26]:
print('S1S2', '\n', add_mult_matrices(M1, M2, '*'))

S1S2 
 [[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

**Quiz p.19, Question 3**

In [33]:
S = np.array([[2, 2], [1, 2]])
S_inv = np.linalg.inv(S)
print(S_inv)

print(S @ S_inv)
print(np.allclose(S @ S_inv, np.eye(2)))

[[ 1.  -1. ]
 [-0.5  1. ]]
[[1. 0.]
 [0. 1.]]
True


**Chap10. Question 1 a)**

In [40]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([-7, 5, 2])
print(A)
print(b)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]
[-7  5  2]


In [41]:
x = np.linalg.solve(A, b)
print(x)

[ 3.  4. -6.]


In [42]:
A @ x

array([-7.,  5.,  2.])

**Chap10. Question 1 b)**

In [43]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([1, -1, 1])

In [44]:
x = np.linalg.solve(A, b)
print(x)

[ 8.  2. -1.]


In [45]:
A @ x

array([ 1., -1.,  1.])

**Chap 12. Question 1**

In [46]:
M = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])

In [47]:
M_inv = np.linalg.inv(M)
print(M_inv)

print(np.allclose(M @ M_inv, np.eye(3)))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [48]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [49]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [50]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
